### PR TITLE
[FIX] wrong class for pagination in solr (Podio bug_45)

### PR DESCRIPTION
**Pull request by vhusaruk92**

### CODE REVIEW

**Review by pixelmatseriks — APPROVED** [review]
good, we don't need the NEJ (No) there anymore ;)

**Review by dmh — CHANGES_REQUESTED** [review]
Seems it will cause new bug. I agree that we need to fix this class `btn-group-justifiedNEJ`, but the problem is, when we remove this part `NEJ` - original class `btn-group-justified` create full width pagination and it is not good, because buttons is too big, better if it aligned to the left. So my proposition is to remove whole this class, but it should be tested properly.

**Comment by vhusaruk92** [comment]
When I change class name "search-result-pagination btn-group btn-group-justifiedNEJ" to "search-result-pagination btn-group btn-group-justified" it looks that very way

screen shot 2016-09-27 at 14 58 16

**Comment by vhusaruk92** [comment]
I can delete "btn-group-justified" and leave "search-result-pagination btn-group"
screen shot 2016-09-27 at 15 07 40
 class and the design won't change at all.

**Comment by vhusaruk92** [comment]
https://github.com/t3kit/felayout_t3kit/pull/23

**Pull request closed without merging**
