### PR TITLE
[FEATURE] New content element "Bootstrap Slider" as basic slider

### PR DESCRIPTION
**Pull request by aennafae**
A new template to use the carousel slider from the Bootstrap package. These changes are needed for a  following pull request in the "theme_t3kit" extension which will contain a new TYPO3 Content Element for this basic Bootstrap slider. We will wait for this request to be accepted before making the request for the TYPO3 Element in the "theme_t3kit" extension.

### CODE REVIEW

**Comment by bauschan** [comment]
+1 for this feature

**Comment by tigeralex** [comment]
+1

**Comment by dmh** [comment]
Hi,

**Thanks for your PR.**

I want to explain little bit our position according Bootstrap carousel slider. For now we are using [Swiper](https://github.com/nolimits4web/Swiper) for carousel slider.

Advantages compare to Bootstrap carousel slider:
- Touch movement
- Images Lazy Loading
- Lot of options. Reach API.
- ...

And in this case I don't see a reason to have both of them active. So I will change your PR little bit. I will add partial `bootstrapSlider.hbs`, but keep commented it in `bootstrap.less` and `bootstrap.js`. It will not be active from start, but yo always can uncomment it and use.

Thanks!

**Comment by aennafae** [comment]
Hi back!

The reason why we decided to make this pull request was because
- the slides don't have the familiar carousel function ( you have to slide back through all images when on last image)
- the fact that the images are integrated as "background-images" from CSS
- in most projects the customers are happy with a simple slider

In times of "Mobile First" we need to have a responsive image switch.
We have solved the lazy loading and the responsive image switch within TYPO3. This features could have been the next features for the Bootstrap Slider in your project.

If we have to uncomment the JS and CSS files for the Bootstrap Slider means that we have to patch the theme_t3kit extension. In this case i would rather override your current slider template in my project extension than write an extension patch - that's one of the benefits of fluid_styled_content.
For this reason the`bootstrapSlider.hbs` partial does not seem useful to us.

Thank you for your time.
Anna

**Comment by dmh** [comment]
Hi,
We added this PR.

And keep in mind that now we have two sliders (js files), so if you need only one of them better to disable second one.

Thanks for feedback and support.

**Pull request merged**
